services:
  app:
    build: .
    container_name: cs-hw-02-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:567234@postgres:5432/cs_db
    networks:
      - cs_default

  postgres:
    image: arm64v8/postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: cs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cs_default

volumes:
  postgres_data:

networks:
  cs_default:
    driver: bridge
